### ISSUE TITLE
Wrong step in Eventing - Run the Application Locally

### ISSUE THREAD

**Issue by sammok83** [SAP-samples/btp-developer-guide-cap#104]
Hi there,

In this part: 
[Run the Application Locally - Eventing](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/eventing/develop/run-app-locally.md), shouldn't step 2 be the command:
**cds mock API_BUSINESS_PARTNER** 

cds watch only gives you services defined in processor-service.cds, whereas srv/external (where API_BUSINESS_PARTNER is defined) won't be shown?

**Comment by navinkrishnan** [comment]
For [Run the Application Locally - Eventing](https://github.com/SAP-samples/btp-developer-guide-cap/blob/main/documentation/eventing/develop/run-app-locally.md), we want to run both the API_BUSINESS_PARTNER mock and the processor-service in a single process, so the events can be shared using local-messaging.
`cds watch` or `cds run --with-mocks` will run both the service.
