### ISSUE TITLE
Issue when trying to use build work zone in a multi tenant scenario, no application in subscriber account 

### ISSUE THREAD

**Issue by tf484** [SAP-samples/btp-developer-guide-cap#120]
Hi I have followed the tutorial, I was able to have the multi-tenancy working successfully without the work zone, however after doing the changes for build work-zone, and doing the subscription in the multitenant account, I cannot see the the application under **HTML5 applications** (Managed Application Router provided by SAP Build Work Zone, standard edition)  in the subscriber account and it cannot find the application when I try in the build workzone in the subscriber account. any suggestions? based also in a video from Devfest, it supposed to appear in the html5 application when I subscribe to the provider account.
thanks in advance

**Comment by gopalanand333** [comment]
Hi @tf484 
The if you and any non-extension landscape you can try there. IF there is a extension landscape please try with this:
Add a new destination for the html5 repo runtime under the destination:

- Name: incident-management_cdm
  ServiceInstanceName: incidents-html5-app-runtime-service
  ServiceKeyName: incidents-html5-app-runtime-service-key
  URL: https://html5-apps-repo-rt.${default-domain}/applications/cdm/<cloud-service-name>
**If you are using a extension landscape, you should replace the ${default-domain} with the mail domain, example : eu10-004 to be used as eu-10**

**Comment by miyasuta** [comment]
The same issue has been posted here. 
https://github.com/SAP-samples/btp-developer-guide-cap/issues/116
The design time destination is maintained as @gopalanand333 suggested, but the application is still not visible in HTML5 applications.

**Comment by gopalanand333** [comment]
Hi @miyasuta  the issue has been fixed and people are able to now try it in trial landscape also
